TEST_PASSWORD = "maria123"

TEST_PASSWORD_NOT_FOUND = "xqzvjkpmw"

TEST_PASSWORD_DATE = "maria31122026"

TEST_PASSWORD_DATE_SLASHES = "maria31/12/2026"

TEST_PASSWORD_REPETITION = "maria111"

TEST_PASSWORD_SEQUENCE = "maria123"

TEST_PASSWORD_REVERSE_SEQUENCE = "maria321"

TEST_PASSWORD_UPPERCASE = "Maria123"

TEST_PASSWORD_TRAILING_SPECIAL = "Maria123!"

TEST_PASSWORD_KEYBOARD = "mariaqwerty"

TEST_PASSWORD_KEYBOARD_REVERSE = "mariaytrewq"

TEST_PASSWORD_KEYBOARD_ZXCVBN = "mariazxcvbn"
